apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-qwen25-72b
  namespace: dac
data:
  provider: "openai_compatible"
  api-key: "sk-xxx"
  base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "qwen2.5-72b-instruct"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-qwen3-32b
  namespace: dac
data:
  provider: "openai_compatible"
  api-key: "sk-xxx"
  base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "qwen3-32b"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-deepseek-v3
  namespace: dac
data:
  provider: "openai_compatible"
  api-key: "sk-xxx"
  base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "deepseek-v3"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-qwen3-coder-480b
  namespace: dac
data:
  provider: "openai_compatible"
  api-key: "sk-xxx"
  base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "qwen3-coder-480b-a35b-instruct"